name: Go

on:
  pull_request:
  merge_group:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
          echo "machine github.com login ${{ secrets.GH_USER }} password ${{ secrets.GH_TOKEN }}" > ~/.netrc
          export GOPRIVATE=github.com/octoposprime/op-be-shared
          go mod tidy
          go get -u -v ./...
          go mod download
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o main ./cmd/service/main.go
  
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
          echo "machine github.com login ${{ secrets.GH_USER }} password ${{ secrets.GH_TOKEN }}" > ~/.netrc
          export GOPRIVATE=github.com/octoposprime/op-be-shared
          go mod tidy
          go get -u -v ./...
          go mod download
      - name: Test with the Go CLI
        run: go test -v -race ./... -coverprofile=./cover.out
      - name: Check Test Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: config/testcoverage.yml